### ISSUE TITLE
RFC-4287: Implements 6.4.2: Structured Extension Elements

### ISSUE THREAD

**Issue by fhiegel** [vidal-community/atom-jaxb#25]
Implements [RFC 4287](https://tools.ietf.org/html/rfc4287): [6.4.2 section](https://tools.ietf.org/html/rfc4287#section-6.4.2)
> Extending Atom > Extension Elements > Structured Extension Elements

> **[6.4.2.  Structured Extension Elements](https://tools.ietf.org/html/rfc4287#section-6.4.2)**
> The root element of a Structured Extension element MUST have at least
> one attribute or child element.  It MAY have attributes, it MAY
> contain well-formed XML content (including character data), or it MAY
> be empty.  Structured Extension elements are Language-Sensitive.
> ```
>  structuredExtensionElement =
>      element * - atom:* {
>          (attribute * { text }+,
>             (text|anyElement)*)
>        | (attribute * { text }*,
>           (text?, anyElement+, (text|anyElement)*))
>       }
> ```
> The structure of a Structured Extension element, including the order
> of its child elements, could be significant.

**Comment by AElMehdiVidal** [comment]
For those having hard time understanding the fragment used in the illustration, they can refer to the documentation of the [RELAX-NG](http://www.relaxng.org/compact-tutorial-20030326.html) schema language.
