### ISSUE TITLE
Information request: entry can be a standalone document ?

### ISSUE THREAD

**Issue by floriangasc** [vidal-community/atom-jaxb#83]
Hi.
(Sorry for my bad english, i am french).

First Thank's for your work. It is appreciated. 

I have request. Entry class has no XmlRootElement, but in rfc it's define an entry can be use as standalone document (https://www.rfc-editor.org/rfc/rfc4287.html#section-4.1.2).
  2 questions ?
1. It's possible to had this annotation (i have make a P.R in case of you think it's a good idea) ?
2. There are any reason why this annotation is not put on Entry class ?

I known with jaxb it's possible to unmarshall without this annotation, but in my case, it is not so easy, as in getting started. And in my case, it's remove a artificial complexity if we can add this annotation. An other solution is to make a constructor protected for use inheritance).

Thanks a lot for your time.

**Comment by jcgay** [comment]
No reason at all, we were just not having the use case to serialize `Entry` as document 😇.
I've answer in #84 

Thanks again 👍
